=== paoloricciuti/ricciuti.me/src/lib/schemas/talks.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"title": "Talk",
	"type": "object",
	"required": ["title", "description", "event"],
	"properties": {
		"title": {
			"type": "string"
		},
		"event": {
			"type": "string"
		},
		"watch": {
			"type": "string",
			"format": "uri"
		},
		"description": {
			"type": "string"
		},
		"slides": {
			"type": "string",
			"format": "uri"
		},
		"date": {
			"type": "string",
			"format": "date"
		}
	}
}

=== paoloricciuti/ricciuti.me/src/lib/talks/5.json
{
	"$schema": "../schemas/talks.json",
	"title": "Hacking SvelteLab",
	"event": "Svelte Summit Spring 2023",
	"watch": "https://youtube.com/watch?v=UKZDcDNAHXY",
	"date": "2023-05-25",
	"description": "Presentation of Sveltelab, the supercharged REPL for sveltekit, winner of the Svelte Hackaton 2023"
}

=== paoloricciuti/ricciuti.me/src/lib/talks/9.json
{
	"$schema": "../schemas/talks.json",
	"title": "Herd your async tasks!",
	"event": "Svelte London Meetup",
	"watch": "https://youtube.com/watch?v=mxM208nCvHc",
	"slides": "https://sheepdog.ricciuti.app",
	"date": "2024-10-30",
	"description": "Asynchronous code is a PITA but it doesn't have to be...follow along to learn about how a sheepdog can help you herd and juggle all your async tasks!"
}

=== paoloricciuti/ricciuti.me/src/lib/talks/10.json
{
	"$schema": "../schemas/talks.json",
	"title": "Surprise! Svelte Secretly Sending Signals",
	"event": "Svelte London Meetup",
	"watch": "https://www.youtube.com/watch?v=s79E0Q9f2YM",
	"date": "2025-02-26",
	"description": "Svelte 5 brought a brand new paradigm on the table of svelte users: Runes.<br /><br />Under the hood Runes uses a popular pattern for fine grained reactivity called Signals. While signals are just an implementation detail for svelte, understanding how they work and why they work and what gotchas they bring is good to be more proficient developing with Svelte.<br/><br/>In this talk we will implement a basic version of a reactivity system with signals and go over the main gotchas."
}

=== paoloricciuti/ricciuti.me/src/lib/talks/1.json
{
	"$schema": "../schemas/talks.json",
	"title": "Presenting SvelteLab",
	"event": "This Week in Svelte",
	"watch": "https://youtube.com/watch?v=H2kOO5mvUQs",
	"date": "2023-04-15",
	"description": "Presentation of Sveltelab, the supercharged REPL for sveltekit, winner of the Svelte Hackaton 2023"
}
